### ISSUE TITLE
Sass Build Problem

### ISSUE THREAD

**Issue by dmreagan** [michaelkrone/generator-material-app#12]
Hello,

I got the following error when trying to build on Linux:

```
gulp build
[16:07:04] Using gulpfile ~/Development/material-app-test/gulpfile.js
[16:07:04] Starting 'sass'...

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn sass ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickDomainCallback (node.js:381:11)
```

Any ideas?

**Comment by michaelkrone** [comment]
Hello,

can you verify Ruby and Sass are installed on your system?
```
$ruby -v
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
$sass -v
Sass 3.4.5 (Selective Steve)
```

**Comment by dmreagan** [comment]
Yeah, that was it. Clearly, I'm new to Sass, but everything's running now. Thanks for the quick response.
