### ISSUE TITLE
error with gulp build

### ISSUE THREAD

**Issue by brunofreitas7** [michaelkrone/generator-material-app#16]
Hi, I followed the steps to generate an app, but when I executed the gulp build command that error is showed:

 gulp build
[13:52:42] Using gulpfile ~/Dev/yeoman-test/gulpfile.js
[13:52:42] Starting 'sass'...

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn sass ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickDomainCallback (node.js:381:11)

Can you help me?

**Comment by brunofreitas7** [comment]
work, needed to install the ruby-sass:
sudo apt-get install ruby-sass
