### ISSUE TITLE
gulp build fails 

### ISSUE THREAD

**Issue by ruizhit** [michaelkrone/generator-material-app#24]
Hi!
I get the following error :

[12:26:21] Using gulpfile ~/Developer/nodejs/yogenerators/gmaterialapp/gulpfile.js
[12:26:21] Starting 'sass'...

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: spawn sass ENOENT
    at exports._errnoException (util.js:849:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:430:9)
    at process._tickDomainCallback (node.js:385:17)

versions:
node v4.1.2
npm v2.14.4

**Comment by michaelkrone** [comment]
Hi.
```
Error: spawn sass ENOENT
```
You need sass to compile the scss files to css. See here: http://sass-lang.com/install

**Comment by ruizhit** [comment]
Thank you @michaelkrone !
