### ISSUE TITLE
Cannot read property 'auth' of undefined

### ISSUE THREAD

**Issue by cmarrero01** [michaelkrone/generator-material-app#32]
When I run 

yo material-app:api multiplayer

I have the next error:

TypeError: Cannot read property 'auth' of undefined
    at Object.prompts.when (/usr/local/lib/node_modules/generator-material-app/generators/api/index.js:44:39)
    at module.exports (/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/run-async/index.js:15:21)
    at AnonymousObservable.__subscribe (/usr/local/lib/node_modules/yo/node_modules/inquirer/lib/ui/prompt.js:121:7)
    at AnonymousObservable.tryCatcher (/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:63:31)
    at setDisposable (/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5741:44)
    at AnonymousObservable.innerSubscribe [as _subscribe] (/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5755:9)
    at AnonymousObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1604:19)
    at AnonymousObservable.__subscribe (/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:2112:21)
    at AnonymousObservable.tryCatcher (/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:63:31)
    at setDisposable (/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5741:44)

**Comment by michaelkrone** [comment]
Should be closed with #38
