### ISSUE TITLE
Error 'UnauthorizedError: jwt malformed' in auth

### ISSUE THREAD

**Issue by Stupidism** [michaelkrone/generator-material-app#96]
``` bash
defaultErrorHandler /api/users/me 200 { [UnauthorizedError: jwt malformed]
  name: 'UnauthorizedError',
  message: 'jwt malformed',
  code: 'invalid_token',
  status: 401,
  inner: { [JsonWebTokenError: jwt malformed] name: 'JsonWebTokenError', message: 'jwt malformed' } }
GET /api/users/me 401 2ms - 407b
UnauthorizedError: jwt malformed
    at /home/stupid/Documents/demos/materialApp/node_modules/express-jwt/lib/index.js:100:22
    at /home/stupid/Documents/demos/materialApp/node_modules/jsonwebtoken/index.js:155:18
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by Stupidism** [comment]
Caused by DateInterceptor converting token into date
