### ISSUE TITLE
EventEmitter depreciation in gulpfile

### ISSUE THREAD

**Issue by mikesterific** [michaelkrone/generator-material-app#98]
Hi, I'm getting the following when attempting 'gulp build':
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: spawn sass ENOENT
  at exports._errnoException (util.js:1007:11)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
  at onErrorNT (internal/child_process.js:348:16)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickDomainCallback (internal/process/next_tick.js:122:9)

**Comment by Stupidism** [comment]
install sass in your machine...

**Comment by michaelkrone** [comment]
See here: http://sass-lang.com/install
