### ISSUE TITLE
gulp-protractor webdriver-manager error

### ISSUE THREAD

**Issue by victorcechinel** [michaelkrone/generator-material-app#99]
```
# Configuration

? Shall I scaffold out a JWT authentication (with users and stuff)? Yes
   create .bowerrc
   create .editorconfig
   create .gitmodules
   create .jscsrc
   create .jshintrc
   create .npmignore
   create bin/server.js
   create bower.json
   create build.xml
   create client/.jshintrc
   create client/.jshintrc-spec
   create client/app/account/account.js
   create client/app/account/login/login.controller.js
   create client/app/account/login/login.html
   create client/app/account/login/login.scss
   create client/app/account/settings/settings.controller.js
   create client/app/account/settings/settings.html
   create client/app/admin/admin.controller.js
   create client/app/admin/admin.html
   create client/app/admin/admin.js
   create client/app/admin/admin.scss
   create client/app/admin/main/main.controller.js
   create client/app/admin/main/main.controller.spec.js
   create client/app/admin/main/main.html
   create client/app/admin/main/main.js
   create client/app/admin/main/main.scss
   create client/app/admin/user/create/create.controller.js
   create client/app/admin/user/create/create.controller.spec.js
   create client/app/admin/user/create/create.html
   create client/app/admin/user/create/create.js
   create client/app/admin/user/create/create.scss
   create client/app/admin/user/list/detail/detail.controller.js
   create client/app/admin/user/list/detail/detail.controller.spec.js
   create client/app/admin/user/list/detail/detail.html
   create client/app/admin/user/list/detail/detail.js
   create client/app/admin/user/list/detail/detail.scss
   create client/app/admin/user/list/edit/edit-password/edit-password.controller.js
   create client/app/admin/user/list/edit/edit-password/edit-password.html
   create client/app/admin/user/list/edit/edit-password/edit-password.scss
   create client/app/admin/user/list/edit/edit.controller.js
   create client/app/admin/user/list/edit/edit.controller.spec.js
   create client/app/admin/user/list/edit/edit.html
   create client/app/admin/user/list/edit/edit.js
   create client/app/admin/user/list/edit/edit.scss
   create client/app/admin/user/list/items/items.controller.js
   create client/app/admin/user/list/items/items.controller.spec.js
   create client/app/admin/user/list/items/items.html
   create client/app/admin/user/list/items/items.js
   create client/app/admin/user/list/items/items.scss
   create client/app/admin/user/list/list.controller.js
   create client/app/admin/user/list/list.controller.spec.js
   create client/app/admin/user/list/list.html
   create client/app/admin/user/list/list.js
   create client/app/admin/user/list/list.scss
   create client/app/admin/user/user.controller.js
   create client/app/admin/user/user.controller.spec.js
   create client/app/admin/user/user.html
   create client/app/admin/user/user.js
   create client/app/admin/user/user.scss
   create client/app/app.controller.js
   create client/app/app.js
   create client/app/components/auth/auth.service.js
   create client/app/components/auth/authinterceptor.service.js
   create client/app/components/auth/user.service.js
   create client/app/components/io/io.service.js
   create client/app/components/list-image/list-image.directive.js
   create client/app/components/list-image/style.scss
   create client/app/components/lodash/lodash.service.js
   create client/app/components/main-menu/main-menu.controller.js
   create client/app/components/main-menu/main-menu.controller.spec.js
   create client/app/components/main-menu/main-menu.directive.js
   create client/app/components/main-menu/main-menu.html
   create client/app/components/main-menu/main-menu.js
   create client/app/components/main-menu/main-menu.scss
   create client/app/components/main-menu/main-menu.service.js
   create client/app/components/main-menu/main-menu.service.spec.js
   create client/app/components/model-definitions/model-definitions.service.js
   create client/app/components/model-definitions/model-definitions.service.spec.js
   create client/app/components/model-input-group/model-input-group.directive.js
   create client/app/components/model-input-group/model-input-group.directive.spec.js
   create client/app/components/model-input-group/model-input-group.html
   create client/app/components/model-input-group/model-input-group.scss
   create client/app/components/model-input-group/model-input/model-input.directive.js
   create client/app/components/model-input-group/model-input/model-input.directive.spec.js
   create client/app/components/model-input-group/model-input/model-input.html
   create client/app/components/model-input-group/model-input/model-input.scss
   create client/app/components/mongoose-error/mongoose-error.directive.js
   create client/app/components/remote-unique/remote-unique.directive.js
   create client/app/components/remote-unique/remote-unique.directive.spec.js
   create client/app/components/repeat-input/repeat-input-directive.spec.js
   create client/app/components/repeat-input/repeat-input.directive.js
   create client/app/components/resource/resource.service.js
   create client/app/components/socket/socket.mock.js
   create client/app/components/socket/socket.service.js
   create client/app/components/toast/toast.html
   create client/app/components/toast/toast.service.js
   create client/app/components/toast/toast.service.spec.js
   create client/app/components/toggle-component/toggle-component.directive.js
   create client/app/components/toggle-component/toggle-component.js
   create client/app/components/toggle-component/toggle-component.scss
   create client/app/components/toggle-component/toggle-component.service.js
   create client/app/components/toggle-component/toggle-component.spec.js
   create client/app/main/main.controller.js
   create client/app/main/main.controller.spec.js
   create client/app/main/main.html
   create client/app/main/main.js
   create client/app/main/main.scss
   create client/assets/images/.gitkeep
   create client/favicon.ico
   create client/index.html
   create client/styles/app.scss
   create client/styles/common.scss
   create client/styles/forms.scss
   create client/styles/sections.scss
   create e2e/main/main.po.js
   create e2e/main/main.spec.js
   create gulp/config.js
   create gulp/tasks/build.js
   create gulp/tasks/dev.js
   create gulp/tasks/reports.js
   create gulp/tasks/tests.js
   create gulpfile.js
   create karma.conf.js
   create package.json
   create protractor.conf.js
   create README.md
   create server/.jshintrc
   create server/.jshintrc-spec
   create server/api/user/index.js
   create server/api/user/user.controller.js
   create server/api/user/user.model.js
   create server/api/user/user.model.spec.js
   create server/api/user/user.socket.js
   create server/app.js
   create server/app.spec.js
   create server/config/env/development.js
   create server/config/env/production.js
   create server/config/env/test.js
   create server/config/express.js
   create server/config/index.js
   create server/config/mongoose.js
   create server/config/seed.js
   create server/config/socketio.js
   create server/lib/auth/auth.service.js
   create server/lib/auth/index.js
   create server/lib/auth/local/index.js
   create server/lib/auth/local/passport.js
   create server/lib/auth/roles.js
   create server/lib/controllers/base.controller.js
   create server/lib/controllers/crud.controller.js
   create server/lib/controllers/crud.controller.spec.js
   create server/lib/controllers/param.controller.js
   create server/lib/controllers/param.controller.spec.js
   create server/lib/middleware/index.js
   create server/lib/responses/errors.js
   create server/lib/responses/index.js
   create server/lib/responses/ok.js
   create server/routes.js
   create server/views/404.html
   create server/views/500.html


I'm all done. Running bower install & npm install for you to install the required dependencies. If this fails, try running the command yourself.


npm WARN deprecated jsonwebtoken@4.2.2: Critical vulnerability fix in v5.0.0. See https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/
npm WARN deprecated jws@2.0.0: Security update: Versions below 3.0.0 are deprecated.
npm WARN deprecated gulp-minify-css@0.3.13: Please use gulp-clean-css
npm WARN deprecated gulp-plato@1.0.2: Deprecated. Just use the `plato` module directly.
npm WARN deprecated lodash@2.2.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
(node:26690) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26690) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26690) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26690) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26690) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26690) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
(node:26690) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26690) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26690) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26690) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26690) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26690) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26690) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26690) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26690) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26690) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26690) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26690) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26690) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26690) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26690) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26690) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26690) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26690) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26690) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26690) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26690) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26690) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26690) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26690) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26690) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26690) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
npm WARN deprecated minimatch@0.4.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN prefer global coffee-script@1.8.0 should be installed with -g
npm WARN prefer global marked@0.3.6 should be installed with -g
npm WARN prefer global jshint@2.9.3 should be installed with -g

> fsevents@1.0.14 install /Users/victorcechinel/projetos/brcasp/app/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/victorcechinel/projetos/brcasp/app/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" is installed via remote

> bson@0.2.22 install /Users/victorcechinel/projetos/brcasp/app/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bson/ext/bson.o

> kerberos@0.0.11 install /Users/victorcechinel/projetos/brcasp/app/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/kerberos/lib/kerberos.o

> ws@0.4.32 install /Users/victorcechinel/projetos/brcasp/app/node_modules/karma/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o

> phantomjs@1.9.20 install /Users/victorcechinel/projetos/brcasp/app/node_modules/phantomjs
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v1.9.19/phantomjs-1.9.8-macosx.zip
Saving to /var/folders/4_/8zz7x2wx44gbzyg07yxl482r0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip
Receiving...
  [======================================--] 96%
Received 9187K total.
Extracting zip contents
Removing /Users/victorcechinel/projetos/brcasp/app/node_modules/phantomjs/lib/phantom
Copying extracted folder /var/folders/4_/8zz7x2wx44gbzyg07yxl482r0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip-extract-1474566008614/phantomjs-1.9.8-macosx -> /Users/victorcechinel/projetos/brcasp/app/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /Users/victorcechinel/projetos/brcasp/app/node_modules/phantomjs/lib/phantom/bin/phantomjs

> app@0.0.0 postinstall /Users/victorcechinel/projetos/brcasp/app
> node ./node_modules/gulp-protractor/node_modules/protractor/bin/webdriver-manager update

module.js:457
    throw err;
    ^

Error: Cannot find module '/Users/victorcechinel/projetos/brcasp/app/node_modules/gulp-protractor/node_modules/protractor/bin/webdriver-manager'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/victorcechinel/.nvm/versions/node/v6.5.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE
npm ERR! app@0.0.0 postinstall: `node ./node_modules/gulp-protractor/node_modules/protractor/bin/webdriver-manager update`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the app@0.0.0 postinstall script 'node ./node_modules/gulp-protractor/node_modules/protractor/bin/webdriver-manager update'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./node_modules/gulp-protractor/node_modules/protractor/bin/webdriver-manager update
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/victorcechinel/projetos/brcasp/app/npm-debug.log
➜  app node ./node_modules/gulp-protractor/node_modules/protractor/bin/webdriver-manager update
module.js:457
    throw err;
    ^
Error: Cannot find module '/Users/victorcechinel/projetos/brcasp/app/node_modules/gulp-protractor/node_modules/protractor/bin/webdriver-manager'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Node version:** v6.5.0
**NPM version:** 3.10.7

**Comment by Stupidism** [comment]
Please search gulp-protractor in issues first and find a solution. Tell me if you still have this issue
